baseURL = "https://the-real-everyday-fix.netlify.app/"
languageCode = "en-us"
title = "The Real Everyday Fix"
theme = "PaperMod"

[params.assets]
  customCSS = ["css/custom.css"]
  disableScrollBarStyle = false

# Enable shortcodes and modules
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
