baseURL = "/"
languageCode = "en-us"
title = "The Real Everyday Fix"
theme = "PaperMod"

[params]
  customCSS = ["css/custom.css"]

[params.assets]
  disableScrollBarStyle = false

# Enable shortcodes and modules
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
