baseURL = "/"
languageCode = "en-us"
title = "The Real Everyday Fix"
theme = "PaperMod"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  # Add PaperMod params as needed
  assets = ["css/custom.css"]

# Enable shortcodes and modules
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
